@extends('layouts.master')

@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-note icon-gradient bg-premium-dark"></i>
            </div>
            <div>Coupon
                <div class="page-title-subheading">Welcome to SPE Admin</div>
            </div>
        </div>

        <div class="page-title-actions">
            <button type="button" data-toggle="modal" data-target="#GenerateCoupon" class="btn-shadow btn btn-info">
                <span class="btn-icon-wrapper pr-2 opacity-7">
                    <i class="fa fa-file-medical fa-w-20"></i>
                </span>
                Generate Coupon
            </button>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="main-card mb-3 card">
            <div class="card-body">
              @if (session('message'))
                <div class="page-title-heading">
                    <div class="alert alert-success">
                        {{ session('message') }}
                    </div>
                </div>
              @endif

              <div class="card-title">Coupon List</div>

              <table class="mb-0 table table-striped">
                  <thead>
                  <tr>
                      <th>#</th>
                      <th>Shop Name</th>
                      <th>Apply Date</th>
                      <th>Coupon</th>
                      <th>Validity</th>
                      <th>Generated By</th>
                      <th>Activated By</th>
                      <th>Status</th>
                  </tr>
                  </thead>
                  <tbody>
                    <?php
                    $sl = 1;
                    foreach($coupons as $coupon):
                    ?>
                      <tr>
                          <th scope="row"><?php echo $sl; ?></th>
                          <td><?php if($coupon->pharmacy_name){ echo $coupon->pharmacy_name; }else{ echo "-"; }  ?></td>
                          <td><?php if($coupon->apply_date){ echo date("jS F, Y", strtotime($coupon->apply_date)); }else{ echo "-"; }  ?></td>
                          <td>
                              <?php 
                                $coupon_details = str_split($coupon->coupon_code, 4);
                                echo "<strong>". $coupon_details[0]. " - " .$coupon_details[1] . " - " . $coupon_details[2] . " - " . $coupon_details[3] . "</strong>"; 
                              ?>
                          </td>
                          <td><?php echo $coupon->coupon_type; ?></td>
                          <td><?php echo $coupon->generated_by; ?></td>
                          <td><?php if($coupon->activated_by){ echo $coupon->activated_by; }else{ echo "-"; }  ?></td>
                          <td><?php if($coupon->status){ echo $coupon->status; }else{ echo "-"; }  ?></td>
                      </tr>
                    <?php
                    $sl++;
                    endforeach;
                    ?>
                  </tbody>
              </table>
                
            </div>
        </div>
    </div>
</div>

@endsection

<!-- modal -->
<div class="modal fade" style="display:none;" id="GenerateCoupon" tabindex="-1" role="dialog" aria-labelledby="GenerateCoupon" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Generate New Coupon</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('generate-coupon') }}">
                    @csrf
                    <div class="form-group row">
                        <label for="coupon_type" class="col-md-4 col-form-label text-md-right">{{ __('Validity') }}</label>
                        <div class="col-md-6">
                            <select name="coupon_type" id="coupon_type" required class="form-control @error('coupon_type') is-invalid @enderror" name="coupon_type">
                                <option value="1MONTH">1 MONTH</option>
                                <option value="3MONTH">3 MONTHS</option>
                                <option value="6MONTH">6 MONTHS</option>
                                <option value="1YEAR">1 YEAR</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Number" class="col-md-4 col-form-label text-md-right">{{ __('No. Of Generated Coupon') }}</label>
                        <div class="col-md-6">
                            <input type="number" min="1" max="10" name="number_of_generated_coupon" required class="form-control form-control-1 input-sm from @error('number_of_generated_coupon') is-invalid @enderror" placeholder="No. Of Generated Coupon" >
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Generate') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End modal -->


